apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  #suspend: true
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.15.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      env:
        GF_SERVER_ROOT_URL: https://homelab-t480s.tailb18fbd.ts.net/grafana
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      grafana.ini:
        server:
          root_url: https://homelab-t480s.tailb18fbd.ts.net/grafana
          serve_from_sub_path: true

    prometheus:
      prometheusSpec:
        externalUrl: "https://homelab-t480s.tailb18fbd.ts.net/prometheus"
        routePrefix: "/prometheus"
        additionalScrapeConfigs:
          name: additional-scrape-configs
          key: additional-scrapes.yaml
