apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: additional-scrape-configs
    files:
      - additional-scrapes.yaml
