apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: "1.0.0" # Pinning the chart version is good practice
      sourceRef:
        kind: HelmRepository
        name: pree-helm-charts
        namespace: flux-system
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        hosts:
          - host: homelab-t480s.tailb18fbd.ts.net
            paths:
              - path: /media/sonarr
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-pvc
      media:
        enabled: true
        type: custom
        volumeSpec:
          persistentVolumeClaim:
            claimName: tv-pvc
        mountPath: /tv
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          persistentVolumeClaim:
            claimName: downloads-pvc
        mountPath: /downloads
