apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: "1Ti" # Using a large nominal size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ops/media-stack/downloads"
